export default {
  index: "API Catalog",
  "developer-utilities": "Developer Utilities",
  "email-domain-validation": "Email & Domain",
  "bulk-email-verification": "Bulk Email Verification",
  "qr-code-generator-api": "QR Code Generator API",
  "qr-code-api-with-logo": "QR Code API with Logo",
  "wifi-qr-code-api": "WiFi QR Code API",
  "ai-content-generator-api": "AI Content Generator API",
  "seo-meta-tags-api": "SEO Meta Tags API",
  "email-validation": "Email Validation",
  "regex-generator": "Regex Generator",
  "regex-explainer": "Regex Explainer",
  "stacktrace-analyzer": "Stacktrace Analyzer",
  "readme-generator": "README Generator",
  "changelog-generator": "Changelog Generator",
  "json-formatter": "JSON Formatter",
  "base64-encoder-decoder": "Base64 Encode/Decode",
  "hash-generator": "Hash Generator",
  "id-generator": "UUID/ULID Generator",
  "url-parser": "URL Parser",
  "ssl-checker": "SSL Checker",
  "dns-analyzer": "DNS Analyzer",
  "url-safety-checker": "URL Safety Checker",
  "security-headers-analyzer": "Security Headers",
  "robots-txt-analyzer": "Robots.txt Analyzer",
  "sitemap-validator": "Sitemap Validator",
  "cors-checker": "CORS Checker",
  resume: "Resume Roadmap",
  appstore: "App Store Roadmap",
  pdf: "PDF Roadmap",
  ocr: "OCR Roadmap",
  content: "Content Tools",
};
